base_model: teknium/OpenHermes-2-Mistral-7B
model_type: MistralForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

chat_template: chatml

datasets:
  - path: ./data/interim/chatbot_train_data_filtered.jsonl
    type: sharegpt

dataset_prepared_path: last_run_prepared
val_set_size: 0.1
output_dir: ./models/eam-bot

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

wandb_project: ea-bot
wandb_entity: michielree-university-of-groningen
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 4
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 2e-5

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch: 4
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens: